<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jwauth"
 *
 * Auto generated by Extension Builder 2015-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'JW Auth',
	'description' => 'Add IP-based authentication',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'projects@jweiland.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);