<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jwauth"
 *
 * Auto generated by Extension Builder 2015-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JW Auth',
    'description' => 'Login to TYPO3 backend with your static IP address',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'projects@jweiland.net',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
